#!/bin/sh
# prerm script for fuckooredoo

set -e

case "$1" in
    remove|upgrade|deconfigure)
        echo "Removing fuckooredoo package..."
    ;;

    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac


# Automatically added by dh_python3
if command -v py3clean >/dev/null 2>&1; then
	py3clean -p fuckooredoo 
else
	dpkg -L fuckooredoo | sed -En -e '/^(.*)\/(.+)\.py$/s,,rm "\1/__pycache__/\2".*,e'
	find /usr/lib/python3/dist-packages/ -type d -name __pycache__ -empty -print0 | xargs --null --no-run-if-empty rmdir
fi

# End automatically added section


exit 0
