#!/bin/sh
# prerm script for fuckooredoo

set -e

case "$1" in
    remove|upgrade|deconfigure)
        echo "Removing fuckooredoo package..."
    ;;

    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
